### ISSUE TITLE
runlock and runstat fails on absolute command paths

### ISSUE THREAD

**Issue by kseistrup** [google/cronutils#5]
`runlock` can't handle absolute command paths, and is explicit about why:

```sh
$ runlock /usr/bin/true
/tmp/cronutils-kseistrup//usr/bin/true.pid: No such file or directory
```

`runstat` probably has the same problem, but is more subtle about why it fails:

```sh
$ runstat /usr/bin/true
mkstemp: No such file or directory
```

Both commands should probably either create the missing path in `/tmp/cronutils-$USER` before running `command`, or substitute the directory separator with some other character, although the latter solution may lead to ambiguous filenames (e.g., `/path/to/command` → `path_to_command` vs. the command `path_to_command` in `$PATH`).

Another solution could be to create a lockfile `sha256(command + args)` and symlink it to `$(basename $command).$PID` to enable the user to find the file.

Sanitizing command paths for double separators and more is probably also a good idea:

```sh
$ pwd                             # we're just at home, having fun
/home/kseistrup
$ ../../usr/bin/date +%Y          # ugly, but it works
2021
$ runlock ../../usr/bin/date +%Y  # runlock will attempt to create a lockfile outside tmp/cronutils-$USER
/tmp/cronutils-kseistrup/../../usr/bin/date.pid: Permission denied
$ runlock /usr/bin/true           # yields unpretty double slash in lock filename
```

**Comment by jaqx0r** [comment]
Thanks for the detailed and amusing report.  Indeed this is a terrible crime.
